from enum import StrEnum


class ErrorCode(StrEnum):
    AUTHENTICATION_FAILED = "AUTHENTICATION_FAILED"
    FORBIDDEN = "FORBIDDEN"
    NOT_FOUND = "NOT_FOUND"
    VALIDATION_FAILED = "VALIDATION_FAILED"
    CONFLICT = "CONFLICT"
    RATE_LIMITED = "RATE_LIMITED"
    CONCURRENCY_LIMIT_REACHED = "CONCURRENCY_LIMIT_REACHED"
    REQUEST_TOO_LARGE = "REQUEST_TOO_LARGE"
    BUDGET_EXCEEDED = "BUDGET_EXCEEDED"
    PROVIDER_UNAVAILABLE = "PROVIDER_UNAVAILABLE"
    TEMPORARY_FAILURE = "TEMPORARY_FAILURE"
    DOCUMENT_NOT_READY = "DOCUMENT_NOT_READY"
    UNSAFE_INPUT = "UNSAFE_INPUT"
    INTERNAL_ERROR = "INTERNAL_ERROR"
